# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2e41ccd06245b59d173dbbc1c1d48cd6034312afd4a6075532fd58b195a0f33a8de99a1dacfb426498730a55feea7693c9138013e0d6d76c6be99848860cd5

test:
  secret_key_base: 4bd9a0caba2a0cbd7e95ae85179e045816e83eca7fea198e37f632a2dcc7185bff1fcf968106fd9231e9becfd0232c6f334ecae3a81014359e2714c6f8f98986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
